[package]
name = "bourh/verifiedgametemplate"
description = ".."
version = "0.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@^1.4.0"
Promise = "evaera/promise@^4.0.0"
Knit = "sleitnick/knit@^1.7.0"
Loader = "sleitnick/loader@^2.0.0"
Signal = "sleitnick/signal@2.0.1"
WaitFor = "sleitnick/wait-for@1.0.0"
